# Quarto Website Design

project:
  type: website

render:
  - "*.qmd"
  - "Curriculum-Vitae/*"
  - "Papers/*"
  - "Books/*"
  - "Blog/*"
  - "!Private/*"          # Private folder: NO Rendering, Do not include in the website

website:
  title: "JeongHo SEO"
  navbar:
    left:
      - href: index.qmd   # Link to the file
        text: Home        # Text to display
      - href: Curriculum-Vitae/
        text: CV
      - href: Papers/
        text: Papers      
      - href: Books/
        text: Books
      - href: Blog/
        text: Blog

format:
  html:
    theme: cosmo
    toc: true
