# Quarto Website Design
# READ Here: https://quarto.org/docs/projects/quarto-projects.html

project:
    type: website                             # Modify Here (default, website, blog, manuscript, book, confluence)
    output-dir: _site

render:
    # Not Rendered files and folders
    - "!**/README.md"                         # README file: Just Description, Do not include in the website
    - "!**/Private/**"                        # Private folder: NO Rendering, Do not include in the website

website:
    title: "JeongHo SEO"
    
    # Navigation Bar
    navbar:
        left:
            # Above buttons in the Left
            - href: index.qmd                 # Link to the file
              text: Home                      # Text to display
            - href: Curriculum-Vitae/
              text: CV
            - href: Papers/
              text: Papers      
            - href: Books/
              text: Books
            - href: Blog/
              text: Blog

        right:
            # Above buttons in the Right
            - icon: github
              href: https://github.com/JeongHo-SEO/

    # Blog/sidebar settings
    sidebar:
        id: "blog-navigation"
        title: "Pho's Notes"
        style: "docked"
        background: "light"
        contents:
            - text: "All"
              href: Blog/index.qmd
            - text: "Statistics"
              href: Blog/Statistics/index.qmd
            - text: "AI"
              href: Blog/AI/index.qmd
            - text: "Mathematics"
              href: Blog/Mathematics/index.qmd

format:
    html:
        theme: cosmo                          # Modify Here  
        toc: true                             # Table of Contents
        include-in-header: google-verification.html    # for google search
