# Quarto Website Design
# READ Here: https://quarto.org/docs/projects/quarto-projects.html

project:
    type: website
    output-dir: .                        # ê²°ê³¼ë¬¼ì„ Books í´ë” ì•ˆì— ìƒì„± (í•˜ìœ„ ë°°í¬ë¥¼ ìœ„í•´ í•„ìš”)

website:
    title: "Published Books"
    site-url: /Books/                     # ğŸ‘ˆ CSS/JS ê²½ë¡œ ì˜¤ë¥˜ í•´ê²° (Assets ë§í¬ ë³´ì •)
    
    # Navigation Bar
    navbar:
        left:
            # Above buttons in the Left
            - href: /index.qmd 
              text: Home
        right:
            # Above buttons in the Right
            - icon: github
              href: https://github.com/JeongHo-SEO/

listing:
    contents: ./                     # Every contents in this folder
    type: grid


format:
    html:
        theme: journal
        toc: true
