# Quarto Website Design
# READ Here: https://quarto.org/docs/projects/quarto-projects.html

project:
    type: blog
    output-dir: .                      # 결과물을 Blog 폴더에 생성

render:
    # index (contents)
    - "*.qmd"
    - "*.md"

    # Not Rendered files and folders
    - "!README.md"
    - "!*/README.md"
    - "!Private/*"

blog:
    title: "Pho's Notes"
    post-date-format: MMMM DD, YYYY

    # Categories
    sections:
        - title: Statistics
          path: Statistics/
        - title: AI
          path: AI/
        - title: Mathematics
          path: Mathematics/

website:
    title: "Pho's Notes"
    site-url: /Blog/                   # CSS/JS 경로 오류 해결
    
    # Navigation Bar
    navbar:
        left:
            - href: index.qmd
              text: Home
            - href: Statistics/
              text: Stat
            - href: AI/
              text: AI      
            - href: Mathematics/
              text: Math

        right:
            # Above buttons in the Right
            - icon: github
              href: https://github.com/JeongHo-SEO/
            - href: https://blog.naver.com/podong_turtle
              text: Daily

format:
    html:
        theme: journal
        toc: true
